### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by insanity54** [azavea/ansible-graphite#8]
I get this error:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 103, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 440, in _load_roles
    roles = self._build_role_dependencies(roles, [], {})
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 251, in _build_role_dependencies
    role_path,role_vars = self._get_role_path(role)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 226, in _get_role_path
    utils.path_dwim(self.basedir, os.path.join('roles', role_name)),
  File "/usr/lib/python2.7/posixpath.py", line 66, in join
    if b.startswith('/'):
AttributeError: 'dict' object has no attribute 'startswith'
```

when running this:

```
ANSIBLE_NOCOWS=1 ansible-playbook ./main.yml --ask-sudo-pass
```

with this playbook:

```
---
- name: installs graphite server
  hosts: worlds
  roles:
    - role: { azavea.graphite, graphite_web_secret_key: "asdfasdifasdoifjsldkf" }
```

ansible 1.9.2

**Comment by hectcastro** [comment]
I believe that the syntax for defining roles in your main playbook is incorrect. It may need to change to something like:

```yaml
---
- name: installs graphite server
  hosts: worlds
  roles:
    - { role: "azavea.graphite", graphite_web_secret_key: "asdfasdifasdoifjsldkf" }
```

**Comment by insanity54** [comment]
yep, that was the problem. thanks.
